# Generated by Django 5.1.7 on 2025-03-22 04:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carwash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Номер телефона должен содержать 11 цифр.', regex='^\\d{11}$')])),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1, message='Рейтинг не может быть меньше 1'), django.core.validators.MaxValueValidator(5, message='Рейтинг не может быть больше 5')])),
                ('is_active', models.BooleanField(default=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carwashes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Автомойка',
                'verbose_name_plural': 'Автомойки',
                'ordering': ['-created_at'],
            },
        ),
    ]
