# Generated by Django 5.1.7 on 2025-03-22 12:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carwash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Номер телефона должен содержать 11 цифр.', regex='^\\d{11}$')])),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1, message='Рейтинг не может быть меньше 1'), django.core.validators.MaxValueValidator(5, message='Рейтинг не может быть больше 5')])),
                ('is_active', models.BooleanField(default=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carwashes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Автомойка',
                'verbose_name_plural': 'Автомойки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Номер телефона должен содержать 11 цифр.', regex='^\\d{11}$')])),
                ('is_active', models.BooleanField(default=True)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('rating', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1, message='Рейтинг не может быть меньше 1'), django.core.validators.MaxValueValidator(5, message='Рейтинг не может быть больше 5')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carwash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='carwash.carwash')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1, message='Рейтинг не может быть меньше 1'), django.core.validators.MaxValueValidator(5, message='Рейтинг не может быть больше 5')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to='carwash.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_from', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'branch'), name='unique_rating')],
            },
        ),
    ]
