# Generated by Django 5.1.7 on 2025-03-22 05:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwash',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1, message='Рейтинг не может быть меньше 1'), django.core.validators.MaxValueValidator(5, message='Рейтинг не может быть больше 5')]),
        ),
    ]
