# Generated by Django 5.1.7 on 2025-03-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0002_rating_description'),
        ('services', '0002_bodytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='bodytypes',
            field=models.ManyToManyField(related_name='branch_bodytypes', to='services.bodytype'),
        ),
    ]
