# Generated by Django 5.1.7 on 2025-05-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0003_branch_bodytypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwash',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
