# Generated by Django 5.1.7 on 2025-03-22 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0003_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='rating_value',
        ),
    ]
