# Generated by Django 5.1.7 on 2025-03-22 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0004_rename_rating_rating_rating_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='carwash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to='carwash.carwash'),
        ),
    ]
