# Generated by Django 5.1.7 on 2025-03-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0005_alter_rating_carwash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwash',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
