version: '3.9'

services:
    backend:
        build:
        context: .
        dockerfile: Dockerfile
        volumes:
            - .:/home/app  # Для разработки, чтобы код в реальном времени подхватывался
        ports:
            - "8000:8000"
        environment:
            - DATABASE_URL=postgres://user:password@db:5432/dbname
        depends_on:
            - db
        # command: poetry run python manage.py runserver 0.0.0.0:8000  # Для разработки

    db:
        image: postgres:15
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=dbname
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"  # Опционально, если хочешь локально к базе цепляться

volumes:
    postgres_data: