services:
    database:
        container_name: database
        image: postgres:15
        restart: always
        env_file:
            - ./.env
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432" 
        networks:
            - carwash-network


    backend:
        container_name: backend
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        volumes:
            - .:/home/app
        ports:
            - "127.0.0.1:8000:8000"
        depends_on:
            - database
        networks:
            - carwash-network

    frontend:
        container_name: frontend
        build:
            context: ./carwash_frontend
            dockerfile: Dockerfile
        restart: always
        networks:
            - carwash-network

    nginx:
        container_name: nginx
        build:
            context: ./nginx
            dockerfile: Dockerfile
        restart: always
        ports:
            - "80:80"
        networks:
            - carwash-network


volumes:
    postgres_data:

networks:
    carwash-network: