services:
    carwash-database:
        image: postgres:15
        restart: always
        env_file:
            - ./.env
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432" 
        networks:
            - carwash-network


    carwash-backend:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        volumes:
            - .:/home/app
        ports:
            - "8000:8000"
        depends_on:
            - carwash-database
        networks:
            - carwash-network

volumes:
    postgres_data:

networks:
    carwash-network: