version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/app  # Для разработки, чтобы код в реальном времени подхватывался
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/dbname
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    command: poetry run python manage.py runserver 0.0.0.0:8000  # Для разработки

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Опционально, если хочешь локально к базе цепляться

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"  # Опционально, для локального доступа

volumes:
  postgres_data:
  redis_data: