# Generated by Django 5.1.7 on 2025-03-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Autofill', max_length=150),
            preserve_default=False,
        ),
    ]
